FROM tomcat:10.1-jdk21-temurin

ARG RAILWAY_PUBLIC_DOMAIN
ARG RAILWAY_PRIVATE_DOMAIN
ARG RAILWAY_PROJECT_NAME
ARG RAILWAY_ENVIRONMENT_NAME
ARG RAILWAY_SERVICE_NAME
ARG RAILWAY_PROJECT_ID
ARG RAILWAY_ENVIRONMENT_ID
ARG RAILWAY_SERVICE_ID

ENV RAILWAY_PUBLIC_DOMAIN=$RAILWAY_PUBLIC_DOMAIN \
    RAILWAY_PRIVATE_DOMAIN=$RAILWAY_PRIVATE_DOMAIN \
    RAILWAY_PROJECT_NAME=$RAILWAY_PROJECT_NAME \
    RAILWAY_ENVIRONMENT_NAME=$RAILWAY_ENVIRONMENT_NAME \
    RAILWAY_SERVICE_NAME=$RAILWAY_SERVICE_NAME \
    RAILWAY_PROJECT_ID=$RAILWAY_PROJECT_ID \
    RAILWAY_ENVIRONMENT_ID=$RAILWAY_ENVIRONMENT_ID \
    RAILWAY_SERVICE_ID=$RAILWAY_SERVICE_ID

WORKDIR /usr/local/tomcat/webapps

RUN rm -rf ./*

RUN apt-get update && \
    apt-get install -y maven

COPY ./target/CCODE.pattern.rest.war ROOT.war

WORKDIR /app

RUN mvn -DskipTests clean install

#RUN --mount=type=cache,id=s/cbcd6488-98bc-4b7a-98d0-a1209477cc8e-/root/.m2,target=/root/.m2 \
#    mvn -DskipTests clean install

RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*

CMD ["catalina.sh", "run"]
